# Reference:
# - https://docs.docker.com/compose/compose-file
# - https://eclipsesource.com/blogs/2018/01/11/authenticating-reverse-proxy-with-keycloak/

services:
  ohif-viewer:
    image: ohif/app:latest
    container_name: ohif-viewer
    restart: always
    # environment:
    #   APP_CONFIG: /usr/share/nginx/html/app-config.js
    volumes:
      - ./ohif-viewer/app-config.js:/usr/share/nginx/html/app-config.js:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/logs:/var/logs/nginx
    ports:
      - 3000:80

  # LINK: https://hub.docker.com/r/jodogne/orthanc-plugins/
  # TODO: Update to use Postgres
  # https://github.com/mrts/docker-postgresql-multiple-databases
  orthanc:
    image: jodogne/orthanc-plugins
    hostname: orthanc
    container_name: orthancPACS
    volumes:
      # Config
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
      # Persist data
      - ./orthanc/db/:/var/lib/orthanc/db/
    restart: unless-stopped
    ports:
      - '4242:4242' # Orthanc REST API
      - '8042:8042' # Orthanc HTTP